name: autoprefixer_transformer
version: 0.3.0
author: Boris Kaul <localvoid@gmail.com>
description: Transfomer that parses css and adds vendor prefixes to CSS rules.
homepage: https://github.com/localvoid/autoprefixer_transformer
environment:
  sdk: '>=1.9.0'
dependencies:
  barback: '>=0.15.0 <0.16.0'
